// client/angular/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';


interface Item {
  id: number;
  userId: string;
  lat: string;
  lon: string;
  description: string;
  image: string;
  keywords: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  standalone: true,
  imports: [CommonModule, FormsModule]
})
export class AppComponent {
  items: Item[] = [];
  tempItem: Item = this.getEmptyItem();

  addItem(): void {
    const newItem: Item = {
      ...this.tempItem,
      id: Date.now() // Using timestamp for unique ID
    };
    this.items.push(newItem);
    this.tempItem = this.getEmptyItem(); // Reset form
  }

  deleteItem(itemId: number): void {
    this.items = this.items.filter(item => item.id !== itemId);
  }

  private getEmptyItem(): Item {
    return {
      id: 0,
      userId: '',
      lat: '',
      lon: '',
      description: '',
      image: '',
      keywords: ''
    };
  }
}

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced.  * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<div class="container mt-4">
  <h1 class="mb-4">FreeCycle</h1>

  <form (ngSubmit)="addItem()" class="row g-3">
    <div class="col-md-6">
      <input type="text" class="form-control" placeholder="User ID" name="user_id" [(ngModel)]="tempItem.userId">
    </div>
    <div class="col-md-3">
      <input type="number" class="form-control" placeholder="Latitude" name="lat" [(ngModel)]="tempItem.lat">
    </div>
    <div class="col-md-3">
      <input type="number" class="form-control" placeholder="Longitude" name="lon" [(ngModel)]="tempItem.lon">
    </div>
    <div class="col-12">
      <textarea class="form-control" rows="3" placeholder="Description" name="description" [(ngModel)]="tempItem.description"></textarea>
    </div>
    <div class="col-md-6">
      <input type="text" class="form-control" placeholder="Image URL" name="image" [(ngModel)]="tempItem.image">
    </div>
    <div class="col-md-6">
      <input type="text" class="form-control" placeholder="Keywords" name="keywords" [(ngModel)]="tempItem.keywords">
    </div>
    <div class="col-12">
      <button type="submit" class="btn btn-primary" data-action="create_item">Create Item</button>
    </div>
  </form>

  <ul class="list-group mt-4">
    <li *ngFor="let item of items" class="list-group-item" [attr.data-field]="item.id">
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <p>{{ item.description }}</p>
          <small>Lat: {{ item.lat }}, Lon: {{ item.lon }}</small>
        </div>
        <button class="btn btn-danger btn-sm" (click)="deleteItem(item.id)" data-action="delete">Delete</button>
      </div>
    </li>
  </ul>
</div>








<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content above * * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced.  * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * End of Placeholder  * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

// client/react/my-app/src/App.js
import React, { useState } from 'react';
import { TextField, Button, List, ListItem, ListItemText, Container, Typography, Box } from '@mui/material';
import DeleteIcon from '@mui/icons-material/Delete';

function App() {
  const [item, setItem] = useState({ user_id: '', lat: '', lon: '', description: '', image: '', keywords: '' });
  const [items, setItems] = useState([]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setItem({ ...item, [name]: value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const newItem = { ...item, id: Date.now() };
    setItems(prevItems => [...prevItems, newItem]);
    setItem({ user_id: '', lat: '', lon: '', description: '', image: '', keywords: '' });
  };

  const handleDelete = (id) => {
    setItems(prevItems => prevItems.filter(item => item.id !== id));
  };

  return (
    <Container>
      <Box id="nav" sx={{ my: 4 }}>
        <Typography variant="h4" component="h1" gutterBottom>
          FreeCycle
        </Typography>
      </Box>
      <Box component="form" onSubmit={handleSubmit} noValidate sx={{ mt: 1 }}>
  <TextField
    margin="normal"
    required
    fullWidth
    id="user_id"
    label="User ID"
    name="user_id"
    autoFocus
    value={item.user_id}
    onChange={handleInputChange}
  />
  <TextField
    margin="normal"
    required
    fullWidth
    id="lat"
    label="Latitude"
    name="lat"
    value={item.lat}
    onChange={handleInputChange}
  />
  <TextField
    margin="normal"
    required
    fullWidth
    id="lon"
    label="Longitude"
    name="lon"
    value={item.lon}
    onChange={handleInputChange}
  />
  <TextField
    margin="normal"
    required
    fullWidth
    id="description"
    label="Description"
    name="description"
    multiline
    rows={4}
    value={item.description}
    onChange={handleInputChange}
  />
  <TextField
    margin="normal"
    required
    fullWidth
    id="image"
    label="Image URL"
    name="image"
    value={item.image}
    onChange={handleInputChange}
  />
  <TextField
    margin="normal"
    required
    fullWidth
    id="keywords"
    label="Keywords"
    name="keywords"
    value={item.keywords}
    onChange={handleInputChange}
  />
  <Button type="submit" data-action="create_item" fullWidth variant="contained" sx={{ mt: 3, mb: 2 }}>
    Create Item
  </Button>
</Box>


<List>
  {items.map((item) => (
    <ListItem 
      key={item.id}
      secondaryAction={
        <Button 
          edge="end" 
          aria-label="delete" 
          onClick={() => handleDelete(item.id)}
          data-action="delete"
        >
          <DeleteIcon />
        </Button>
      }
    >
      <ListItemText 
        primary={item.description} 
        secondary={`Lat: ${item.lat}, Lon: ${item.lon}`} 
      />
      <span data-field="id" style={{ display: 'none' }}>{item.id}</span>
    </ListItem>
  ))}
</List>

    </Container>
  );
}

export default App;
